apiVersion: v1
kind: Service
metadata:
  name: loyalty-abuse
  labels:
    app: loyalty-abuse
spec:
  selector:
    app: loyalty-abuse
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
